title: Thought Dumpster
description: Yet Another Internet Blog
navbar-links:
  Archives: "/alex.ciobanu.org/index.html"
  About Me: "about"

avatar: "/img/avatar.jpeg"
navbar-col: "#353535"
navbar-text-col: "#e8e8e8"
navbar-children-col: "#353535"
page-col: "#2a2a29"
page-text-col: "#f0e7d5"
page-header-text-col: "#e8e8e8"
page-post-preview-col: "#808080"
link-col: "#f4bf75"
hover-col: "#ff8800"
footer-col: "#353535"
footer-text-col: "#e8e8e8"
footer-link-col: "#ffcc00"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

author:
  name: Alexandru Ciobanu
social-network-links:
  rss: true
  email: "alex+git@ciobanu.org"
  github: pavkam
  linkedin: ciobanua
  stackoverflow: "8291909/pavkam"
  instagram: pavkam_
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

url-pretty: "pavkam.github.io"
gtag: "GTM-TH68XWQ"
excerpt_length: 50
title-separator: "-"
timezone: "Europe/Dublin"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

link-tags: true
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
    - /alex.ciobanu.org
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
plugins:
  - jekyll-paginate
  - jekyll-sitemap
