title: Thought Dumpster
description: Yet Another Internet Blog
navbar-links:
  About Me: "about"
  Tags: "tags"
  Feed: "feed"
  Archive: "/alex.ciobanu.org/index.html"

avatar: "/assets/img/avatar.jpeg"
round-avatar: true

author: Alexandru Ciobanu
social-network-links:
  rss: true
  email: "alex+git@ciobanu.org"
  github: pavkam
  linkedin: ciobanua
  stackoverflow: "8291909/pavkam"
  instagram: pavkam_
share-links-active:
  twitter: true
  linkedin: true
  url-pretty: "pavkam.github.io"
google_analytics: "UA-143067975-1"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
title-separator: "-"

navbar-col: "#353535"
navbar-text-col: "#e8e8e8"
navbar-children-col: "#353535"
page-col: "#2a2a29"
text-col: "#f0e7d5"
link-col: "#f4bf75"
hover-col: "#ff8800"
footer-col: "#353535"
footer-text-col: "#e8e8e8"
footer-link-col: "#ffcc00"
page-header-text-col: "#e8e8e8"
page-post-preview-col: "#808080"

timezone: "Europe/Dublin"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
